import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const members = [
      { id: 11, name: 'Afghanistan' },
      { id: 12, name: 'Albania' },
      { id: 13, name: 'Algeria' },
      { id: 14, name: 'Andorra' },
      { id: 15, name: 'Angola' },
      { id: 16, name: 'Antigua and Barbuda' },
      { id: 17, name: 'Argentina' },
      { id: 18, name: 'Armenia' },
      { id: 19, name: 'Australia' },
      { id: 20, name: 'Austria' },
      { id: 21, name: 'Azerbaijan' },
      { id: 22, name: 'Bahamas' },
      { id: 23, name: 'Bahrain' },
      { id: 24, name: 'Bangladesh' },
      { id: 25, name: 'Barbados' },
      { id: 26, name: 'Belarus' },
      { id: 27, name: 'Belgium' },
      { id: 28, name: 'Belize' },
      { id: 29, name: 'Benin' },
      { id: 30, name: 'Bhutan' },
      { id: 31, name: 'Bolivia' },
      { id: 32, name: 'Bosnia and Herzegovina' },
      { id: 33, name: 'Botswana' },
      { id: 34, name: 'Brazil' },
      { id: 35, name: 'Brunei' },
      { id: 36, name: 'Bulgaria' },
      { id: 37, name: 'Burkina Faso' },
      { id: 38, name: 'Burma (Myanmar)' },
      { id: 39, name: 'Burundi' },
      { id: 40, name: 'Cambodia' },
      { id: 41, name: 'Cameroon' },
      { id: 42, name: 'Canada' },
      { id: 43, name: 'Cape Verde' },
      { id: 44, name: 'Central African Republic' },
      { id: 45, name: 'Chad' },
      { id: 46, name: 'Chile' },
      { id: 47, name: 'China2' },
      { id: 48, name: 'Colombia' },
      { id: 49, name: 'Comoros' },
      { id: 50, name: 'Congo, Rep. of' },
      { id: 51, name: 'Congo, Dem. Rep. of' },
      { id: 52, name: 'Costa Rica' },
      { id: 53, name: 'Côte d\'Ivoire' },
      { id: 54, name: 'Croatia' },
      { id: 56, name: 'Cuba' },
      { id: 57, name: 'Cyprus' },
      { id: 58, name: 'Czech Republic' },
      { id: 59, name: 'Denmark' },
      { id: 60, name: 'Djibouti' },
      { id: 61, name: 'Dominica' },
      { id: 62, name: 'Dominican Republic' },
      { id: 63, name: 'East Timor' },
      { id: 64, name: 'Ecuador' },
      { id: 65, name: 'Egypt' },
      { id: 66, name: 'El Salvador' },
      { id: 67, name: 'Equatorial Guinea' },
      { id: 68, name: 'Eritrea' },
      { id: 69, name: 'Estonia' },
      { id: 70, name: 'Ethiopia' },
      { id: 71, name: 'Fiji' },
      { id: 72, name: 'Finland' },
      { id: 73, name: 'France' },
      { id: 74, name: 'Gabon' },
      { id: 75, name: 'Gambia' },
      { id: 76, name: 'Georgia' },
      { id: 77, name: 'Germany' },
      { id: 78, name: 'Ghana' },
      { id: 79, name: 'Greece' },
      { id: 80, name: 'Grenada' },
      { id: 81, name: 'Guatemala' },
      { id: 82, name: 'Guinea' },
      { id: 83, name: 'Guinea-Bissau' },
      { id: 84, name: 'Guyana' },
      { id: 85, name: 'Haiti' },
      { id: 86, name: 'Honduras' },
      { id: 87, name: 'Hungary' },
      { id: 88, name: 'Iceland' },
      { id: 89, name: 'India' },
      { id: 90, name: 'Indonesia' },
      { id: 91, name: 'Iran' },
      { id: 92, name: 'Iraq' },
      { id: 93, name: 'Ireland' },
      { id: 94, name: 'Israel' },
      { id: 95, name: 'Italy' },
      { id: 96, name: 'Jamaica' },
      { id: 97, name: 'Japan' },
      { id: 98, name: 'Jordan' },
      { id: 99, name: 'Kazakhstan' },
      { id: 100, name: 'Kenya' },
      { id: 101, name: 'Kiribati' },
      { id: 102, name: 'Korea, North' },
      { id: 103, name: 'Korea, South' },
      { id: 104, name: 'Kuwait' },
      { id: 105, name: 'Kyrgyzstan' },
      { id: 106, name: 'Laos' },
      { id: 107, name: 'Latvia' },
      { id: 108, name: 'Lebanon' },
      { id: 109, name: 'Lesotho' },
      { id: 110, name: 'Liberia' },
      { id: 111, name: 'Libya' },
      { id: 112, name: 'Liechtenstein' },
      { id: 113, name: 'Lithuania' },
      { id: 114, name: 'Luxembourg' },
      { id: 115, name: 'Macedonia5' },
      { id: 116, name: 'Madagascar' },
      { id: 117, name: 'Malawi' },
      { id: 118, name: 'Malaysia' },
      { id: 119, name: 'Maldives' },
      { id: 120, name: 'Mali' },
      { id: 121, name: 'Malta' },
      { id: 122, name: 'Marshall Islands' },
      { id: 123, name: 'Mauritania' },
      { id: 124, name: 'Mauritius' },
      { id: 125, name: 'Mexico' },
      { id: 126, name: 'Micronesia' },
      { id: 127, name: 'Moldova' },
      { id: 128, name: 'Monaco' },
      { id: 129, name: 'Mongolia' },
      { id: 130, name: 'Montenegro4, 6' },
      { id: 131, name: 'Morocco' },
      { id: 132, name: 'Mozambique' },
      { id: 133, name: 'Namibia' },
      { id: 134, name: 'Nauru' },
      { id: 135, name: 'Nepal' },
      { id: 136, name: 'Netherlands' },
      { id: 137, name: 'New Zealand' },
      { id: 138, name: 'Nicaragua' },
      { id: 139, name: 'Niger' },
      { id: 140, name: 'Nigeria' },
      { id: 141, name: 'Norway' },
      { id: 142, name: 'Oman' },
      { id: 143, name: 'Pakistan' },
      { id: 144, name: 'Palau' },
      { id: 145, name: 'Panama' },
      { id: 146, name: 'Papua New Guinea' },
      { id: 147, name: 'Paraguay' },
      { id: 148, name: 'Peru' },
      { id: 149, name: 'Philippines' },
      { id: 150, name: 'Poland' },
      { id: 151, name: 'Portugal' },
      { id: 152, name: 'Qatar' },
      { id: 153, name: 'Romania' },
      { id: 154, name: 'Russia' },
      { id: 155, name: 'Rwanda' },
      { id: 156, name: 'St. Kitts and Nevis' },
      { id: 157, name: 'St. Lucia' },
      { id: 158, name: 'St. Vincent and the Grenadines' },
      { id: 159, name: 'Samoa' },
      { id: 160, name: 'San Marino' },
      { id: 161, name: 'São Tomé and Príncipe' },
      { id: 162, name: 'Saudi Arabia' },
      { id: 163, name: 'Senegal' },
      { id: 164, name: 'Serbia6' },
      { id: 165, name: 'Seychelles' },
      { id: 166, name: 'Sierra Leone' },
      { id: 167, name: 'Singapore' },
      { id: 168, name: 'Slovakia3' },
      { id: 169, name: 'Slovenia' },
      { id: 170, name: 'Solomon Islands' },
      { id: 171, name: 'Somalia' },
      { id: 172, name: 'South Africa' },
      { id: 173, name: 'South Sudan' },
      { id: 174, name: 'Spain' },
      { id: 175, name: 'Sri Lanka' },
      { id: 176, name: 'Sudan' },
      { id: 177, name: 'Suriname' },
      { id: 178, name: 'Swaziland' },
      { id: 179, name: 'Sweden' },
      { id: 180, name: 'Switzerland4' },
      { id: 181, name: 'Syria' },
      { id: 182, name: 'Tajikistan' },
      { id: 183, name: 'Tanzania' },
      { id: 184, name: 'Thailand' },
      { id: 185, name: 'Togo' },
      { id: 186, name: 'Tonga' },
      { id: 187, name: 'Trinidad and Tobago' },
      { id: 188, name: 'Tunisia' },
      { id: 189, name: 'Turkey' },
      { id: 190, name: 'Turkmenistan' },
      { id: 191, name: 'Tuvalu' },
      { id: 192, name: 'Uganda' },
      { id: 193, name: 'Ukraine' },
      { id: 194, name: 'United Arab Emirates' },
      { id: 195, name: 'United Kingdom' },
      { id: 196, name: 'United States' },
      { id: 197, name: 'Uruguay' },
      { id: 198, name: 'Uzbekistan' },
      { id: 199, name: 'Vanuatu' },
      { id: 200, name: 'Venezuela' },
      { id: 201, name: 'Vietnam' },
      { id: 202, name: 'Yemen' },
      { id: 203, name: 'Zambia' },
      { id: 204, name: 'Zimbabwe' },
    ];
    return {members};
  }
  /*createDbCommittees() {
    const committees [
      { id: 'GA1', name: 'committee'},
      { id: 'GA2', name: 'committee'},
      { id: 'GA3', name: 'committee'},
      { id: 'GA4', name: 'committee'},
      { id: 'GA6', name: 'committee'},
      { id: 'APS', name: 'committee'},
      { id: 'ASE', name: 'committee'},
      { id: 'SCO', name: 'committee'},
      { id: 'CSW', name: 'committee'},
      { id: 'HCR', name: 'committee'},
      { id: 'USC', name: 'committee'},
      { id: 'UDP', name: 'committee'},
      { id: 'WHO', name: 'committee'},
      { id: 'AAU', name: 'committee'},
      { id: 'ROA', name: 'committee'},
      { id: 'CR1', name: 'committee'},
      { id: 'CR2', name: 'committee'},
    ];
    return committees;
  }*/
}
